export const projects = [
  {
    id: 'can-do',
    title: 'CAN/DO',
    category: 'Kinetic collection',
    description: 'Seven cans. Zero restraint.',
    color: '#c9e673',
    background: '#e4e8db',
    number: '01',
  },
  {
    id: 'sneaker-studio',
    title: 'Sole Studio',
    category: 'Suspended motion',
    description: 'A little lift. A different perspective.',
    color: '#ff7448',
    background: '#ff6334',
    number: '02',
  },
  {
    id: 'keyboard-builder',
    title: 'Key / Form',
    category: 'Order & disorder',
    description: 'Every piece finds its way home.',
    color: '#b8abeb',
    background: '#d2ed64',
    number: '03',
  },
  {
    id: 'perfume-collection',
    title: 'Essence',
    category: 'Light & glass',
    description: 'A different kind of atmosphere.',
    color: '#bf904c',
    background: '#f2e5cd',
    number: '04',
  },
  {
    id: 'vinyl-room',
    title: 'Side A',
    category: 'In the groove',
    description: 'Take the long way around.',
    color: '#e59e76',
    background: '#ce572f',
    number: '05',
  },
  {
    id: 'watch-explorer',
    title: 'Second Nature',
    category: 'Mechanical study',
    description: 'Time, taken apart.',
    color: '#aabdcf',
    background: '#a6b5c5',
    number: '06',
  },
  {
    id: 'miniature-city',
    title: 'Small Hours',
    category: 'World in miniature',
    description: 'Watch a neighborhood wake up.',
    color: '#9ac4b0',
    background: '#9ec8da',
    number: '07',
  },
  {
    id: 'car-garage',
    title: 'After Hours',
    category: 'Night drive',
    description: 'Nowhere to be. Every reason to go.',
    color: '#e3cb4e',
    background: '#bfcd84',
    number: '08',
  },
  {
    id: 'coffee-journey',
    title: 'Daily Ritual',
    category: 'From bean to cup',
    description: 'Slow down. Make a little coffee.',
    color: '#bb8867',
    background: '#e1c69e',
    number: '09',
  },
  {
    id: 'film-camera',
    title: 'Light / Leak',
    category: 'Through the lens',
    description: 'Hold on to the light.',
    color: '#ef6947',
    background: '#e46542',
    number: '10',
  },
  {
    id: 'glass-garden',
    title: 'Glass Garden',
    category: 'A living miniature',
    description: 'A whole world under glass.',
    color: '#bedb65',
    background: '#b6d85c',
    number: '11',
  },
  {
    id: 'lift-off',
    title: 'Lift Off',
    category: 'Beyond the atmosphere',
    description: 'From standing still to somewhere new.',
    color: '#ef6543',
    background: '#84b7de',
    number: '12',
  },
  {
    id: 'insert-coin',
    title: 'Insert Coin',
    category: 'Out of the screen',
    description: 'One credit. Another dimension.',
    color: '#c9f15d',
    background: '#a089cf',
    number: '13',
  },
  {
    id: 'paper-trails',
    title: 'Paper Trails',
    category: 'The art of the fold',
    description: 'A single sheet learns to fly.',
    color: '#ed653c',
    background: '#74b9d3',
    number: '14',
  },
  {
    id: 'deep-blue',
    title: 'Deep Blue',
    category: 'Beneath the surface',
    description: 'Find a little light in the deep.',
    color: '#8de5ec',
    background: '#16364e',
    number: '15',
  },
];
