export const projects = [
  {
    id: 'can-do',
    title: 'CAN/DO',
    category: 'Kinetic collection',
    description: 'Seven cans. Zero restraint.',
    color: '#c9e673',
    background: '#e4e8db',
    number: '01',
  },
  {
    id: 'sneaker-studio',
    title: 'Sole Studio',
    category: 'Material study',
    description: 'Find your next colorway.',
    color: '#ff7448',
    background: '#eee6df',
    number: '02',
  },
  {
    id: 'keyboard-builder',
    title: 'Key / Form',
    category: 'Interactive instrument',
    description: 'Make some noise.',
    color: '#b8abeb',
    background: '#e8e5ee',
    number: '03',
  },
  {
    id: 'perfume-collection',
    title: 'Essence',
    category: 'Light & glass',
    description: 'A different kind of atmosphere.',
    color: '#bf904c',
    background: '#eae5dc',
    number: '04',
  },
  {
    id: 'vinyl-room',
    title: 'Side A',
    category: 'Listening room',
    description: 'Put something good on.',
    color: '#e59e76',
    background: '#e9ded4',
    number: '05',
  },
  {
    id: 'watch-explorer',
    title: 'Second Nature',
    category: 'Mechanical study',
    description: 'Time, taken apart.',
    color: '#aabdcf',
    background: '#e2e7e9',
    number: '06',
  },
  {
    id: 'miniature-city',
    title: 'Small Hours',
    category: 'World in miniature',
    description: 'Watch a neighborhood wake up.',
    color: '#9ac4b0',
    background: '#e1e8e2',
    number: '07',
  },
  {
    id: 'car-garage',
    title: 'After Hours',
    category: 'Design garage',
    description: 'Your color. Your angle.',
    color: '#e3cb4e',
    background: '#e8e5d8',
    number: '08',
  },
  {
    id: 'coffee-journey',
    title: 'Daily Ritual',
    category: 'From bean to cup',
    description: 'Slow down. Make a little coffee.',
    color: '#bb8867',
    background: '#e9e1d9',
    number: '09',
  },
];
