export const projects = [
  {
    id: 'can-do',
    title: 'CAN/DO',
    category: 'Kinetic collection',
    description: 'Seven cans. Zero restraint.',
    color: '#c9e673',
    background: '#e4e8db',
    number: '01',
  },
  {
    id: 'sneaker-studio',
    title: 'Sole Studio',
    category: 'Suspended motion',
    description: 'A little lift. A different perspective.',
    color: '#ff7448',
    background: '#ff6334',
    number: '02',
  },
  {
    id: 'keyboard-builder',
    title: 'Key / Form',
    category: 'Order & disorder',
    description: 'Every piece finds its way home.',
    color: '#b8abeb',
    background: '#d2ed64',
    number: '03',
  },
  {
    id: 'perfume-collection',
    title: 'Essence',
    category: 'Light & glass',
    description: 'A different kind of atmosphere.',
    color: '#bf904c',
    background: '#f2e5cd',
    number: '04',
  },
  {
    id: 'vinyl-room',
    title: 'Side A',
    category: 'In the groove',
    description: 'Take the long way around.',
    color: '#e59e76',
    background: '#ce572f',
    number: '05',
  },
  {
    id: 'watch-explorer',
    title: 'Second Nature',
    category: 'Mechanical study',
    description: 'Time, taken apart.',
    color: '#aabdcf',
    background: '#a6b5c5',
    number: '06',
  },
  {
    id: 'miniature-city',
    title: 'Small Hours',
    category: 'World in miniature',
    description: 'Watch a neighborhood wake up.',
    color: '#9ac4b0',
    background: '#9ec8da',
    number: '07',
  },
  {
    id: 'car-garage',
    title: 'After Hours',
    category: 'Night drive',
    description: 'Nowhere to be. Every reason to go.',
    color: '#e3cb4e',
    background: '#bfcd84',
    number: '08',
  },
  {
    id: 'coffee-journey',
    title: 'Daily Ritual',
    category: 'From bean to cup',
    description: 'Slow down. Make a little coffee.',
    color: '#bb8867',
    background: '#e1c69e',
    number: '09',
  },
];
